/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/databases": {
    /** List all databases */
    get: {
      responses: {
        /** @description List of databases */
        200: {
          content: {
            "application/json": components["schemas"]["Database"][];
          };
        };
      };
    };
    /** Create a new database */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            backupLocation: string;
            project?: string;
          };
        };
      };
      responses: {
        /** @description Database created */
        201: {
          content: {
            "application/json": components["schemas"]["Database"];
          };
        };
      };
    };
  };
  "/databases/{name}": {
    /** Delete a database */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Database deleted */
        200: {
          content: never;
        };
      };
    };
  };
  "/projects": {
    /** List all projects */
    get: {
      responses: {
        /** @description List of projects */
        200: {
          content: {
            "application/json": components["schemas"]["Project"][];
          };
        };
      };
    };
    /** Create a new project */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            backupLocation: string;
          };
        };
      };
      responses: {
        /** @description Project created */
        201: {
          content: {
            "application/json": components["schemas"]["Project"];
          };
        };
      };
    };
  };
  "/projects/{name}": {
    /** Delete a project */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Project deleted */
        200: {
          content: never;
        };
      };
    };
  };
  "/projects/{name}/databases": {
    /** List databases in a project */
    get: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description List of databases in project */
        200: {
          content: {
            "application/json": components["schemas"]["Database"][];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Database: {
      name: string;
      status: string;
      project?: string;
      host?: string;
      port?: number;
      username?: string;
      database?: string;
    };
    Project: {
      id: string;
      name: string;
      backupLocation: string;
      databases?: components["schemas"]["Database"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
