apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devdb.fullname" . }}
  labels:
    {{- include "devdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devdb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "devdb.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}