apiVersion: apps/v1
kind: Deployment
metadata:
  name: devdb-api
  namespace: devdb
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devdb-api
  template:
    metadata:
      labels:
        app: devdb-api
    spec:
      serviceAccountName: devdb  # Use the created service account
      containers:
      - name: devdb-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
    env:
      - name: BACKUP_LOCATION
        valueFrom:
          configMapKeyRef:
            name: {{ .Release.Name }}-backup-config
            key: BACKUP_LOCATION