apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devdb-api
  namespace: devdb
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devdb-api
            port:
              number: 5000