replicaCount: 1

image:
  repository: ghcr.io/meido-ai/devdb-api
  tag: latest
  pullPolicy: Always

api:
  logLevel: info

backupLocation: "/backup"

aws:
  region: us-west-2
  ebs:
    # Set to true to enable EBS optimizations and volume snapshots
    enabled: false
    # Storage class to use for database volumes
    storageClass: ebs-sc
    # Snapshot class to use for volume snapshots
    snapshotClass: ebs-snapshot-class
    # Default volume size for database PVCs
    volumeSize: 10Gi
    # IOPS for GP3 volumes
    iops: 3000
    # Throughput for GP3 volumes (MB/s)
    throughput: 125
    # Enable volume encryption
    encrypted: true

ingress:
  enabled: true
  annotations:
    # Default to Application Load Balancer
    kubernetes.io/ingress.class: alb
    # External facing load balancer
    alb.ingress.kubernetes.io/scheme: internet-facing
    # IP target type for ALB
    alb.ingress.kubernetes.io/target-type: ip
    # Default to HTTP only. For HTTPS, override these in your values file
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # Optional: ACM certificate configuration
    # alb.ingress.kubernetes.io/certificate-arn: ""
    # alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    # alb.ingress.kubernetes.io/ssl-redirect: "443"

s3:
  bucket: devdb-backups
  # Optional: specify a prefix for all backup objects
  prefix: ""