# Number of API replicas to run
replicaCount: 1

image:
  repository: ghcr.io/meido-ai/devdb-api
  tag: latest
  pullPolicy: Always

api:
  logLevel: info

aws:
  # AWS Region for all AWS services
  region: eu-west-1
  ebs:
    # Set to true to enable EBS optimizations
    enabled: true
    # Storage class to use for database volumes
    storageClass: ebs-sc
    # Enable volume snapshots (requires snapshot controller)
    snapshots:
      enabled: false
      # Only used if snapshots.enabled is true
      class: ebs-snapshot-class
    # Default volume size for database PVCs
    volumeSize: 10Gi
    # IOPS for GP3 volumes
    iops: 3000
    # Throughput for GP3 volumes (MB/s)
    throughput: 125
    # Enable volume encryption
    encrypted: true

# Load Balancer configuration
loadBalancer:
  api:
    enabled: true
    annotations: {}
  database:
    enabled: true
    annotations: {}
    # Port range for PostgreSQL databases (54321-54518)
    portRange:
      start: 54321
      end: 54518

# Service configurations
services:
  api:
    name: devdb-api
    port: 5000
    type: ClusterIP
  redis:
    name: devdb-redis
    port: 6379
    type: ClusterIP
    volumeSize: 1Gi
  postgres:
    name: shared-postgres-service
    port: 5432
    type: ClusterIP

# S3 configuration for database backups
s3:
  # S3 bucket for storing database backups
  bucket: devdb-backups
  # Optional: specify a prefix for all backup objects
  prefix: ""

# Resource requests and limits
resources:
  api:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  redis:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"