{{- if and .Values.aws.ebs.enabled .Values.aws.ebs.snapshots.enabled }}
# IAM policy for snapshot operations
apiVersion: iam.aws.amazon.com/v1
kind: IAMPolicy
metadata:
  name: ebs-snapshot-policy
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "ec2:CreateSnapshot",
            "ec2:DeleteSnapshot",
            "ec2:GetSnapshotState",
            "ec2:DescribeSnapshots",
            "ec2:ModifyVolume",
            "ec2:DescribeVolumes",
            "ec2:CreateVolume",
            "ec2:DeleteVolume",
            "ec2:DescribeVolumesModifications"
          ],
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": [
            "kms:CreateGrant",
            "kms:ListGrants",
            "kms:RevokeGrant",
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt*",
            "kms:GenerateDataKey*",
            "kms:DescribeKey"
          ],
          "Resource": "*"
        }
      ]
    }
{{- end }}
