apiVersion: v1
kind: ConfigMap
metadata:
  name: devdb-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.aws.region | quote }}
  AWS_EBS_ENABLED: {{ .Values.aws.ebs.enabled | quote }}
  LOG_LEVEL: {{ .Values.api.logLevel | quote }}
  KUBERNETES_NAMESPACE: {{ .Release.Namespace }}