apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-restore-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  restore-backup.sh: |
    #!/bin/bash
    
    # Start Postgres in the background
    docker-entrypoint.sh postgres &
    POSTGRES_PID=$!
    
    # Wait for Postgres to be ready
    until pg_isready -h localhost -U $POSTGRES_USER; do
      sleep 1
    done
    
    if [ ! -z "$DB_BACKUP_PATH" ]; then
      echo "Restoring backup from $DB_BACKUP_PATH"
      pg_restore -U $POSTGRES_USER -d $POSTGRES_DB $DB_BACKUP_PATH
    else
      echo "No backup path provided, starting with empty database"
    fi
    
    # Wait for the PostgreSQL process
    wait $POSTGRES_PID
