apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.postgres.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "devdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  ports:
    - protocol: TCP
      port: {{ .Values.services.postgres.port }}
      targetPort: {{ .Values.services.postgres.port }}
