apiVersion: v1
kind: ServiceAccount
metadata:
  name: devdb
  namespace: devdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devdb-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "services", "persistentvolumeclaims", "persistentvolumes", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devdb-role-binding
subjects:
- kind: ServiceAccount
  name: devdb
  namespace: devdb
roleRef:
  kind: ClusterRole
  name: devdb-role
  apiGroup: rbac.authorization.k8s.io