apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.redis.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  ports:
  - port: {{ .Values.services.redis.port }}
    targetPort: {{ .Values.services.redis.port }}
  selector:
    app.kubernetes.io/name: {{ include "devdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
