apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.services.redis.name }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  storageClassName: {{ .Values.aws.ebs.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.redis.volumeSize }}
