apiVersion: v1
kind: Service
metadata:
  name: devdb-api
  namespace: devdb
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app: devdb-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000