apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.api.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: {{ include "devdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
  - protocol: TCP
    port: {{ .Values.services.api.port }}
    targetPort: {{ .Values.services.api.port }}