{{- if or .Values.loadBalancer.api.enabled .Values.loadBalancer.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nlb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=10,preserve_client_ip.enabled=true,proxy_protocol_v2.enabled=false,deregistration_delay.connection_termination.enabled=true
    {{- if .Values.loadBalancer.api.enabled }}
    {{- with .Values.loadBalancer.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if .Values.loadBalancer.database.enabled }}
    {{- with .Values.loadBalancer.database.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  type: LoadBalancer
  ports:
  {{- if .Values.loadBalancer.api.enabled }}
  - name: https
    port: 443
    targetPort: 5000
    protocol: TCP
    appProtocol: https
  {{- end }}
  {{- if .Values.loadBalancer.database.enabled }}
  - name: postgres-base
    port: {{ .Values.loadBalancer.database.portRange.start }}
    targetPort: 5432
    protocol: TCP
    appProtocol: postgresql
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "devdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
